//! HF-oracle gate for the DSA indexer forward.
//!
//! The oracle side is `tools/accuracy/glm52_oracle.py --stage indexer`
//! (transformers 5.13.0.dev0). It runs layer-0 attention on a seeded input and
//! captures `hidden`, `cos`, `sin`, `q_resid`, and `topk_indices` as probes in
//! a safetensors file. This test loads the same probes, feeds them through the
//! Rust indexer forward, and asserts set-overlap on the top-k indices
//! (FlashInfer vs torch.topk tie-break on 1-ULP logit ties differs; exact match
//! is impossible, so we allow 1/2048 divergence).
//!
//! Run (H200 + checkpoint + probes):
//! ```text
//! OPENINFER_TEST_MODEL_PATH=/data/models/GLM-5.2-FP8 \
//! OPENINFER_DEEPGEMM_ROOT=openinfer-kernels/third_party/DeepGEMM \
//! CUDA_HOME=/usr/local/cuda \
//!   cargo test --release -p openinfer-glm52 --features glm52 --lib indexer_oracle -- --ignored --nocapture
//! ```
//!
//! Prerequisites:
//! 1. Generate probes: `python tools/accuracy/glm52_oracle.py --model-path /data/models/GLM-5.2-FP8 \
//!    --ctx 4096 --seed 0x5eed604d --layer 0 --precision fp8sim --stage indexer --emit safetensors \
//!    --out /tmp/glm52_oracle_probes.safetensors`
//! 2. The probes file must be at `/tmp/glm52_oracle_probes.safetensors`.

use std::collections::HashSet;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result, ensure};
use half::bf16;
use sha2::{Digest, Sha256};

use openinfer_kernels::ops::{GLM52_INDEXER_TOPK, Glm52IndexerCacheLayout};
use openinfer_kernels::tensor::DeviceContext;

use crate::fp8::Glm52ProjBytes;
use crate::indexer::{Glm52IndexerLayerWeights, glm52_indexer_cache_fill, glm52_indexer_forward};

// ---- oracle provenance ----
// Generated by: tools/accuracy/glm52_oracle.py --model-path /data/models/GLM-5.2-FP8 \
//     --ctx 4096 --seed 0x5eed604d --layer 0 --precision fp8sim --stage indexer
// transformers=5.13.0.dev0 torch=2.12.1+cu130
const ORACLE_CTX: usize = 4096;
const ORACLE_HIDDEN_DIGEST: &str = "7f1235f1bf66b263";
// topk_indices[4095] digest: 9516c827dcf88140 (provenance only — loaded from safetensors at runtime)

const HIDDEN: usize = 6144;
const Q_LORA: usize = 2048;
const INDEX_HEAD_DIM: usize = 128;
const CACHE_BLOCK_SIZE: usize = 64; // DeepGEMM paged MQA requires BLOCK_KV=64
const NUM_SMS: usize = 132;

fn bf16_digest(data: &[bf16]) -> String {
    let mut hasher = Sha256::new();
    for v in data {
        hasher.update(v.to_bits().to_le_bytes());
    }
    hex::encode(&hasher.finalize()[..8])
}

struct Layer0IndexerTensors {
    by_name: std::collections::BTreeMap<String, Vec<u8>>,
}

impl Layer0IndexerTensors {
    fn load(model_path: &Path) -> Result<Self> {
        let index: serde_json::Value = serde_json::from_str(&std::fs::read_to_string(
            model_path.join("model.safetensors.index.json"),
        )?)?;
        let weight_map = index["weight_map"]
            .as_object()
            .context("weight_map missing")?;
        let prefix = "model.layers.0.self_attn.indexer";
        let mut by_shard: std::collections::BTreeMap<String, Vec<String>> =
            std::collections::BTreeMap::default();
        for (name, shard) in weight_map {
            if name.starts_with(prefix) {
                by_shard
                    .entry(shard.as_str().context("shard not a string")?.to_owned())
                    .or_default()
                    .push(name.clone());
            }
        }
        let mut by_name = std::collections::BTreeMap::new();
        for (shard, names) in by_shard {
            let mmap = crate::weights::mmap_file(&model_path.join(&shard))?;
            let st = safetensors::SafeTensors::deserialize(mmap.as_ref())?;
            for name in names {
                by_name.insert(name.clone(), st.tensor(&name)?.data().to_vec());
            }
        }
        Ok(Self { by_name })
    }

    fn bytes(&self, name: &str) -> Result<&[u8]> {
        self.by_name
            .get(name)
            .map(Vec::as_slice)
            .with_context(|| format!("layer-0 indexer tensor {name} not loaded"))
    }

    fn proj(&self, stem: &str, n: usize, k: usize) -> Result<Glm52ProjBytes<'_>> {
        Ok(Glm52ProjBytes {
            weight: self.bytes(&format!("{stem}.weight"))?,
            scale: self.bytes(&format!("{stem}.weight_scale_inv"))?,
            n,
            k,
        })
    }
}

fn load_indexer_layer0(ctx: &DeviceContext, model_path: &Path) -> Result<Glm52IndexerLayerWeights> {
    let t = Layer0IndexerTensors::load(model_path)?;
    let p = "model.layers.0.self_attn.indexer";
    Glm52IndexerLayerWeights::from_host(
        ctx,
        &t.proj(&format!("{p}.wq_b"), 32 * 128, Q_LORA)?,
        &t.proj(&format!("{p}.wk"), 128, HIDDEN)?,
        t.bytes(&format!("{p}.weights_proj.weight"))?,
        t.bytes(&format!("{p}.k_norm.weight"))?,
        t.bytes(&format!("{p}.k_norm.bias"))?,
    )
}

#[test]
#[ignore = "requires H200 + GLM-5.2-FP8 checkpoint + DeepGEMM env"]
fn indexer_oracle_gate() -> Result<()> {
    let model_path = std::env::var_os("OPENINFER_TEST_MODEL_PATH")
        .map_or_else(|| PathBuf::from("models/GLM-5.2-FP8"), PathBuf::from);
    let probes_path = std::env::var_os("OPENINFER_ORACLE_PROBES_PATH").map_or_else(
        || PathBuf::from("/tmp/glm52_oracle_probes.safetensors"),
        PathBuf::from,
    );
    let position = ORACLE_CTX - 1;

    // ---- load oracle probes from safetensors ----
    let mmap = crate::weights::mmap_file(&probes_path)?;
    let st = safetensors::SafeTensors::deserialize(mmap.as_ref())?;

    let hidden_data = st.tensor("hidden")?.data();
    ensure!(
        hidden_data.len() == ORACLE_CTX * HIDDEN * 2,
        "hidden size mismatch"
    );
    let hidden_host: &[bf16] = unsafe {
        std::slice::from_raw_parts(hidden_data.as_ptr().cast::<bf16>(), ORACLE_CTX * HIDDEN)
    };
    let hidden_digest = bf16_digest(hidden_host);
    ensure!(
        hidden_digest == ORACLE_HIDDEN_DIGEST,
        "hidden digest {hidden_digest} != oracle {ORACLE_HIDDEN_DIGEST}: \
         stale probes — regenerate with tools/accuracy/glm52_oracle.py"
    );

    let cos_data = st.tensor("cos")?.data();
    ensure!(cos_data.len() == ORACLE_CTX * 64 * 2, "cos size mismatch");
    let cos_host: &[bf16] =
        unsafe { std::slice::from_raw_parts(cos_data.as_ptr().cast::<bf16>(), ORACLE_CTX * 64) };

    let sin_data = st.tensor("sin")?.data();
    ensure!(sin_data.len() == ORACLE_CTX * 64 * 2, "sin size mismatch");
    let sin_host: &[bf16] =
        unsafe { std::slice::from_raw_parts(sin_data.as_ptr().cast::<bf16>(), ORACLE_CTX * 64) };

    let qr_data = st.tensor("q_resid")?.data();
    ensure!(
        qr_data.len() == ORACLE_CTX * Q_LORA * 2,
        "q_resid size mismatch"
    );
    let qr_host: &[bf16] =
        unsafe { std::slice::from_raw_parts(qr_data.as_ptr().cast::<bf16>(), ORACLE_CTX * Q_LORA) };
    let q_resid_last: &[bf16] = &qr_host[position * Q_LORA..(position + 1) * Q_LORA];

    let topk_data = st.tensor("topk_indices")?.data();
    ensure!(
        topk_data.len() == ORACLE_CTX * GLM52_INDEXER_TOPK * 4,
        "topk size mismatch"
    );
    let topk_all: &[i32] = unsafe {
        std::slice::from_raw_parts(
            topk_data.as_ptr().cast::<i32>(),
            ORACLE_CTX * GLM52_INDEXER_TOPK,
        )
    };
    let oracle_topk: &[i32] =
        &topk_all[position * GLM52_INDEXER_TOPK..(position + 1) * GLM52_INDEXER_TOPK];

    // ---- load indexer weights ----
    let ctx = DeviceContext::new()?;
    let w = load_indexer_layer0(&ctx, &model_path)?;

    // ---- cache setup ----
    let cache_blocks = ORACLE_CTX.div_ceil(CACHE_BLOCK_SIZE);
    let cache_layout = Glm52IndexerCacheLayout {
        cache_blocks,
        cache_block_size: CACHE_BLOCK_SIZE,
        cache_block_stride_bytes: CACHE_BLOCK_SIZE * (INDEX_HEAD_DIM + 4),
    };
    let cache_bytes = cache_layout.min_cache_bytes()?;
    let mut index_k_cache = ctx.stream.alloc_zeros::<u8>(cache_bytes)?;

    let block_table_host: Vec<i32> = (0..cache_blocks as i32).collect();
    let mut block_table = ctx.stream.alloc_zeros::<i32>(cache_blocks)?;
    ctx.stream
        .memcpy_htod(&block_table_host, &mut block_table)?;

    // ---- fill cache for positions 0..position-1 ----
    let mut hidden_buf = ctx.stream.alloc_zeros::<bf16>(HIDDEN)?;
    let mut cos_buf = ctx.stream.alloc_zeros::<bf16>(32)?;
    let mut sin_buf = ctx.stream.alloc_zeros::<bf16>(32)?;
    let mut slot_buf = ctx.stream.alloc_zeros::<i64>(1)?;
    for pos in 0..position {
        let h = &hidden_host[pos * HIDDEN..(pos + 1) * HIDDEN];
        ctx.stream.memcpy_htod(h, &mut hidden_buf)?;
        ctx.stream
            .memcpy_htod(&cos_host[pos * 64..pos * 64 + 32], &mut cos_buf)?;
        ctx.stream
            .memcpy_htod(&sin_host[pos * 64..pos * 64 + 32], &mut sin_buf)?;
        ctx.stream.memcpy_htod(&[pos as i64], &mut slot_buf)?;
        glm52_indexer_cache_fill(
            &ctx,
            &w,
            &hidden_buf,
            &cos_buf,
            &sin_buf,
            &mut index_k_cache,
            cache_layout,
            &slot_buf,
        )?;
    }

    // ---- last position inputs ----
    let last_hidden_host = &hidden_host[position * HIDDEN..(position + 1) * HIDDEN];
    let mut last_hidden = ctx.stream.alloc_zeros::<bf16>(HIDDEN)?;
    ctx.stream.memcpy_htod(last_hidden_host, &mut last_hidden)?;

    let mut q_resid = ctx.stream.alloc_zeros::<bf16>(Q_LORA)?;
    ctx.stream.memcpy_htod(q_resid_last, &mut q_resid)?;

    let mut cos = ctx.stream.alloc_zeros::<bf16>(32)?;
    let mut sin = ctx.stream.alloc_zeros::<bf16>(32)?;
    ctx.stream
        .memcpy_htod(&cos_host[position * 64..position * 64 + 32], &mut cos)?;
    ctx.stream
        .memcpy_htod(&sin_host[position * 64..position * 64 + 32], &mut sin)?;

    let slot_mapping_host = vec![position as i64];
    let mut slot_mapping = ctx.stream.alloc_zeros::<i64>(1)?;
    ctx.stream
        .memcpy_htod(&slot_mapping_host, &mut slot_mapping)?;

    let seq_lens_host = vec![(position + 1) as i32];
    let mut seq_lens = ctx.stream.alloc_zeros::<i32>(1)?;
    ctx.stream.memcpy_htod(&seq_lens_host, &mut seq_lens)?;

    // ---- run indexer forward ----
    let topk = glm52_indexer_forward(
        &ctx,
        &w,
        &last_hidden,
        &q_resid,
        &cos,
        &sin,
        &mut index_k_cache,
        cache_layout,
        &slot_mapping,
        &block_table,
        &seq_lens,
        NUM_SMS,
        ORACLE_CTX,
    )?;

    // ---- assert set-overlap with oracle ----
    // Threshold is 2000/2048 (not 2047) because the production path uses fp8
    // GEMM (DeepGEMM) while the oracle uses Fp8SimLinear (f32 matmul with
    // quant-dequant). The fp8 precision loss causes ~35 boundary mismatches
    // where logit values are nearly tied. A threshold of 2000 catches real bugs
    // (RoPE failure ~1024, wrong scale ~1024, missing ReLU ~1717) while
    // allowing fp8 boundary noise.
    let topk_host = ctx.stream.clone_dtoh(&topk)?;

    let rust_set: HashSet<i32> = topk_host.iter().copied().filter(|&v| v >= 0).collect();
    let oracle_set: HashSet<i32> = oracle_topk.iter().copied().collect();

    let overlap = rust_set.intersection(&oracle_set).count();
    let min_required = 2000;

    ensure!(
        overlap >= min_required,
        "indexer topk set-overlap {overlap} < required {min_required} \
         (rust set size {}, oracle set size {})",
        rust_set.len(),
        oracle_set.len()
    );

    eprintln!("indexer oracle gate: overlap {overlap}/2048 (required >= {min_required})");
    Ok(())
}
